create table m_users
(
	id bigint generated by default as identity (maxvalue 2147483647)
		constraint m_users_pkey
			primary key,
	active boolean,
	password varchar not null,
	username varchar(50),
	email varchar not null,
	phone_number varchar,
	picture_name varchar,
	activation_code varchar
);

alter table m_users owner to testuser;

create unique index m_users_username_uindex
	on m_users (username);

create table m_roles
(
	user_id bigint not null
		constraint m_roles_m_users_id_fk
			references m_users
				on update cascade on delete cascade,
	role_name varchar(255)
);

alter table m_roles owner to testuser;

create table m_messages
(
	id bigint generated by default as identity (maxvalue 2147483647)
		constraint m_messages_pkey
			primary key,
	tag varchar(255),
	text varchar,
	user_id bigint not null
		constraint m_messages_m_users_id_fk
			references m_users,
	filename varchar,
	topic_name varchar(255) not null,
	time timestamp not null
);

alter table m_messages owner to testuser;

create table m_comments
(
	id bigserial not null
		constraint m_comments_pk
			primary key,
	message_id bigint not null
		constraint m_comments_m_messages_id_fk
			references m_messages
				on update cascade on delete cascade,
	text varchar not null,
	user_id bigint not null
		constraint m_comments_m_users_id_fk
			references m_users,
	time timestamp not null,
	parent_id bigint
);

alter table m_comments owner to testuser;

create unique index m_comments_id_uindex
	on m_comments (id);

